### ISSUE TITLE
Bot does not refresh its cache of a user's responses

### ISSUE THREAD

**Issue by einsteinsci** [trambelus/UserSim#9]
I first used user simulator a couple months ago, and at the time I had recently posted to /r/Xenoblade_Chronicles a lot. So I wasn't surprised to see the response use XCX terms like "Telethia Plume", "TP Gain Up XX Augment", and "Ultra Infinite armor". However, since then I've hardly posted to it at all, and instead to /r/SSBPM, /r/tf2, and /r/feedthebeast. I just ran user simulator on myself again today, expecting Smash Bros terminology like "wavedash", "counter-pick", and "GCC". Instead it's still using terminology I use in /r/Xenoblade_Chronicles, even though not one of my past 25 posts have been to that subreddit. So, I think the bot is caching a user's responses the first time the user runs it, and never updating the cache, even if the last time the user ran it was months ago.

If this is the case, simply storing the time when the data is stored for a user, and updating the user's last 25 posts if the user runs the bot when the cache is more than a day (or a week) old, would fix this.

**Comment by trambelus** [comment]
Cache refreshing was implemented in 8afa7b7c. Since it reads 1000 recent comments, not 25, this might not always be apparent.
